### PR TITLE
Make Historian the head of Historian David Crouch

### PR DESCRIPTION
**Pull request by AngledLuffa**

### CODE REVIEW

**Comment by nschneid** [comment]
This is a special construction for combining a role or title with the name of an individual. We tentatively decided that the role/title should be a modifier (because it can be omitted), and a good name for the deprel would be `nmod:desc` ("descriptor"). But we have not implemented this policy yet.

**Comment by AngledLuffa** [comment]
Here are a few instances of this in EWT:

```
# sent_id = weblog-blogspot.com_dakbangla_20050311135387_ENG_20050311_135387-0169
# text = A report by the Center for Disease Control of interviews with AMI employees (as well as detailed interviews by author Leonard Cole) ...
21      author  author  NOUN    NN      Number=Sing     22      compound        22:compound     _
22      Leonard Leonard PROPN   NNP     Number=Sing     19      nmod    19:nmod:by      _
23      Cole    Cole    PROPN   NNP     Number=Sing     22      flat    22:flat SpaceAfter=No

# sent_id = weblog-blogspot.com_dakbangla_20041119231111_ENG_20041119_231111-0010
# text = According to Professor S D Muni, ...
3       Professor       Professor       PROPN   NNP     Number=Sing     36      obl     36:obl:according_to     _
4       S       S       PROPN   NNP     Number=Sing     3       flat    3:flat  _
5       D       D       PROPN   NNP     Number=Sing     3       flat    3:flat  _
6       Muni    Muni    PROPN   NNP     Number=Sing     3       flat    3:flat  SpaceAfter=No

# sent_id = email-enronsent31_01-0005
# text = After talking with Professors Titman, Ronn, Brown and Jemison, ...
1       After   after   SCONJ   IN      _       2       mark    2:mark  _
2       talking talk    VERB    VBG     Tense=Pres|VerbForm=Part        15      advcl   15:advcl:after  _
3       with    with    ADP     IN      _       4       case    4:case  _
4       Professors      Professor       PROPN   NNPS    Number=Plur     2       obl     2:obl:with      _
5       Titman  Titman  PROPN   NNP     Number=Sing     4       flat    4:flat  SpaceAfter=No

# sent_id = email-enronsent31_01-0015
# text = Professor Ronn:
1       Professor       Professor       PROPN   NNP     Number=Sing     0       root    0:root  _
2       Ronn    Ronn    PROPN   NNP     Number=Sing     1       flat    1:flat  SpaceAfter=No
3       :       :       PUNCT   :       _       1       punct   1:punct _

# sent_id = newsgroup-groups.google.com_alt.animals_02c2d614bfbf6b20_ENG_20050223_232900-0022
# text = OSU forestry professors William Ripple and Robert Beschta ...
1       OSU     OSU     PROPN   NNP     Number=Sing     3       compound        3:compound      _
2       forestry        forestry        NOUN    NN      Number=Sing     3       compound        3:compound      _
3       professors      professor       NOUN    NNS     Number=Plur     4       nmod:desc       4:nmod:desc     _
4       William William PROPN   NNP     Number=Sing     10      nsubj   10:nsubj        _
5       Ripple  Ripple  PROPN   NNP     Number=Sing     4       flat    4:flat  _

# sent_id = newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0046
# text = <<Doctor RODERIGO LOPEZ (1525 -1594) was the Portugese Jewish doctor accused by Essex of trying to poison Queen Elizabeth.
2       Doctor  Doctor  PROPN   NNP     Number=Sing     14      nsubj   14:nsubj        _
3       RODERIGO        Roderigo        PROPN   NNP     Number=Sing     2       flat    2:flat  _
4       LOPEZ   Lopez   PROPN   NNP     Number=Sing     2       flat    2:flat  _

# sent_id = reviews-170650-0008
# text = Doctor Gonzales and his entire staff are the most professional people I have ever dealt with.
1       Doctor  Doctor  PROPN   NNP     Number=Sing     11      nsubj   11:nsubj        _
2       Gonzales        Gonzales        PROPN   NNP     Number=Sing     1       flat    1:flat  _

# sent_id = reviews-170650-0012
# text = Thank you Doctor Gonzales, Doctor Stout, Eva Marie and the entire staff!
1       Thank   thank   VERB    VBP     Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin   0       root    0:root  _
2       you     you     PRON    PRP     Case=Acc|Person=2|PronType=Prs  1       obj     1:obj   _
3       Doctor  Doctor  PROPN   NNP     Number=Sing     1       vocative        1:vocative      _
4       Gonzales        Gonzales        PROPN   NNP     Number=Sing     3       flat    3:flat  SpaceAfter=No
5       ,       ,       PUNCT   ,       _       6       punct   6:punct _
6       Doctor  Doctor  PROPN   NNP     Number=Sing     3       conj    1:vocative|3:conj:and   _
7       Stout   Stout   PROPN   NNP     Number=Sing     6       flat    6:flat  SpaceAfter=No

# sent_id = reviews-288100-0002
# newpar id = reviews-288100-p0002
# text = I began seeing Dr. Romanick back in 2000...
4       Dr.     Dr.     PROPN   NNP     Number=Sing     3       obj     3:obj   _
5       Romanick        Romanick        PROPN   NNP     Number=Sing     4       flat    4:flat  _

# newdoc id = reviews-148971
# sent_id = reviews-148971-0001
# newpar id = reviews-148971-p0001
# text = Dr. Strzalka at Flagship CVTS is not a good doctor
1       Dr.     Dr.     PROPN   NNP     Number=Sing     10      nsubj   10:nsubj        _
2       Strzalka        Strzalka        PROPN   NNP     Number=Sing     1       flat    1:flat  _
```

So, more often than not, the title is the head, at least for the titles I searched for.  Certainly could expand that search.  Would rather just focus on the one issue now and do a more global fix later

**Comment by nschneid** [comment]
Fair enough to make it `flat` for now. See: UniversalDependencies/UD_English-EWT#59

**Comment by AngledLuffa** [comment]
We will just have to remember that this exists if'n the new standard is eventually adopted!

**Comment by AngledLuffa** [comment]
Got it.  So in the above, we'd have `nmod:desc(Strzalka, Dr), nmod:desc(Leonard, author)` etc?

**Comment by nschneid** [comment]
Yes

**Comment by AngledLuffa** [comment]
I started going through PUD, about 23% in (up to `Dr Lee`), and found a few questions which could use some clarification.

`"..." Dr Lee adds` should look like this now?

```
23	Dr	Dr	PROPN	NNP	Number=Sing	24	nmod:desc	24:nmod:desc	_
24	Lee	Lee	PROPN	NNP	Number=Sing	25	nsubj	25:nsubj	_
25	adds	add	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	4	parataxis	4:parataxis	SpaceAfter=No
```

Presumably `Mr`, `Mrs`, etc would also qualify?

```
# sent_id = n01013005
# Mr Osborne
# Osborne the head, nmod:desc(Osborne, Mr)?

1	Mr	Mr	PROPN	NNP	Number=Sing	2	nmod:desc	2:nmod:desc	_
2	Osborne	Osborne	PROPN	NNP	Number=Sing	3	nsubj	3:nsubj	_

Mr Panvalkar

6	Mr	Mr	PROPN	NNP	Number=Sing	7	nmod:desc	7:nmod:desc	_
7	Panvalkar	Panvalkar	PROPN	NNP	Number=Sing	8	nsubj	8:nsubj	_
```

What about Mr in a possessive?

```
9	Mr.	Mr.	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
10-11	Comey's	_	_	_	_	_	_	_	_
10	Comey	Comey	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
11	's	's	PART	POS	_	10	case	10:case	_

9	Mr.	Mr.	PROPN	NNP	Number=Sing	10	nmod:desc	10:nmod:desc	_
10-11	Comey's	_	_	_	_	_	_	_	_
10	Comey	Comey	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
11	's	's	PART	POS	_	10	case	10:case	_
```

What about other phrases with noun descriptions of other nouns?  Listing all of them here so that they are easy to go back and search for:

```
Obama special assistant Kori Schulman
SaskTel unlimited data customer Lindsay Gay
expectant mother Margaret Boemer
the Donald Trump impersonator John Di Domenico
British Ministry of Defence maps
are hoping to snatch it back with their **candidate Sarah Olney**
A **Donald Trump victory**
Nazi regime
That 3% rate also applies to **Nectar cardholders**
to the **TV presenter Chris Packham**
UK spy agency GCHQ
```

Some of them I think would fit, others not, but I'm curious where you think the line is

Appositives stay appositive?

```
Joe Sternlieb, president of the Georgetown BID
Jesse LaBrocca, founder of Hack Forums
Erik Solheim, head of UN Environment
Trump's wife, Melania Trump
The Ontario Independent Police Review Director, Gerry McNeilly
```

**Comment by nschneid** [comment]
Guidelines at https://universaldependencies.org/en/dep/nmod-desc.html. An important criterion is whether a determiner would be expected were it not for the name. 

- Obama special assistant Kori Schulman
- SaskTel unlimited data customer Lindsay Gay
- expectant mother Margaret Boemer
- UK spy agency GCHQ

are all cases without a determiner, thus `nmod:desc`.

**Comment by AngledLuffa** [comment]
Trying to figure out what that criterion means...

I saw *Dr. Pritchett* for a new hip

vs

I saw *the doctor* for a new hip

whereas you can "snatch it back with their candidate" with no determiner, so therefore "candidate" and "Sarah" are not `nmod_desc`?

**Comment by nschneid** [comment]
In English, possessives and numerals can take the place of what UD calls determiners: The candidate has arrived. One candidate has arrived. Their candidate has arrived. America's candidate has arrived.

A singular count common noun normally cannot be bare: *Candidate has arrived.

BUT in the construction where a common noun precedes a name, the noun can be bare: Candidate Jim Banks has arrived.

"Candidate" can be omitted, but the name cannot, so we take the name to be the head and "candidate" to be a modifier. Same goes for formal titles like "Dr.".

If a determiner/numeral/possessive precedes the noun, this would be `appos` instead as there are two "full" nominals: Our candidate Jim Banks has arrived. appos(candidate, Jim)

**Comment by AngledLuffa** [comment]
Got it, thanks.  I propose adding more of an explanation to the description page for `nmod:desc`.  Currently it says `determinerless` which is a bit vague

Also wondering: common nouns have the second word as the head, but proper nouns the first?  So we get this

```
25	cost	cost	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	14	conj	14:conj:and	_
26	chief	chief	NOUN	NN	Number=Sing	27	compound	27:compound	_
27	executive	executive	NOUN	NN	Number=Sing	28	nmod:desc	28:nmod:desc	_
28	Martin	Martin	PROPN	NNP	Number=Sing	25	iob	25:iob	_
29	Winterkorn	Winterkorn	PROPN	NNP	Number=Sing	28	flat	28:flat	_
30	his	his	PRON	PRP$	Gender=Masc|Number=Sing|Person=3|Poss=Yes|PronType=Prs	31	nmod:poss	31:nmod:poss	_
31	job	job	NOUN	NN	Number=Sing	25	obj	25:obj	SpaceAfter=No
```

and how about when the title crosses an MWT boundary (the possessive above) - treat it the same as any other title?

```
9	Mr.	Mr.	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
10-11	Comey's	_	_	_	_	_	_	_	_
10	Comey	Comey	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
11	's	's	PART	POS	_	10	case	10:case	_

---->

9	Mr.	Mr.	PROPN	NNP	Number=Sing	10	nmod:desc	10:nmod:desc	_
10-11	Comey's	_	_	_	_	_	_	_	_
10	Comey	Comey	PROPN	NNP	Number=Sing	12	nmod:poss	12:nmod:poss	_
11	's	's	PART	POS	_	10	case	10:case	_
```

**Comment by AngledLuffa** [comment]
and things like `Eon’s fixed rate tariff costs £760 and **Avro Energy customers** would pay...`

`Avro Energy` does not get the `nmod:desc` treatment, right?

**Comment by nschneid** [comment]
> Got it, thanks. I propose adding more of an explanation to the description page for `nmod:desc`. Currently it says `determinerless` which is a bit vague

Good point, replaced with "bare"!

> Also wondering: common nouns have the second word as the head, but proper nouns the first? So we get this

Flat structures (often personal names) technically use the first word as head but in principle none of the words can be distinguished as the head.

Aside from expressions that are [flat](https://universaldependencies.org/u/dep/flat), a series of nouns (common or proper) is usually headed by the last one: an Avro customer = compound(customer, Avro) (can be shortened to "a customer" but not ordinarily "an Avro").

> and how about when the title crosses an MWT boundary (the possessive above) - treat it the same as any other title?

Yeah, the MWT is an orthographic property, irrelevant to the tree structure.

> `Avro Energy` does not get the `nmod:desc` treatment, right?

Right, the reason there is no determiner/possessive/numeral there is because phrases headed by a plural noun do not require any.

**Comment by AngledLuffa** [comment]
> Good point, replaced with "bare"!

More clear, thanks, but perhaps some counterexamples would help make it even more clear

**Comment by AngledLuffa** [comment]
Keeping most of the conversation here instead of spreading it out...

What about when there *could* be no determiner, but there is one anyway?  You could say `... of a campaign by Egyptian pharoah Thutmose III`

```
The Canaanite city was destroyed in a fire, presumably in the wake of a campaign by **the Egyptian pharaoh Thutmose III**.
In 1566, a league of about 400 members of the nobility presented a petition to **the governor Margaret of Parma**, to suspend persecution until the rest had returned.
```

How about demonym in place of title?

```
A fundamental change in working principles was brought about by **Scotsman James Watt**.
```

Is this a different circumstance?  Although I suppose you can't possibly say "Macedonian eastern boder" or "river Nestus" without "the", so these don't count as titles, right?

```
The Macedonian eastern border with Thrace was now secured at the river Nestus (Mesta).
```

**Comment by nschneid** [comment]
> Keeping most of the conversation here instead of spreading it out...
> 
> What about when there _could_ be no determiner, but there is one anyway? You could say `... of a campaign by Egyptian pharoah Thutmose III`
> 
> ```
> The Canaanite city was destroyed in a fire, presumably in the wake of a campaign by **the Egyptian pharaoh Thutmose III**.
> In 1566, a league of about 400 members of the nobility presented a petition to **the governor Margaret of Parma**, to suspend persecution until the rest had returned.
> ```

`appos` with the determiner, `nmod:desc` without.

> How about demonym in place of title?
> 
> ```
> A fundamental change in working principles was brought about by **Scotsman James Watt**.
> ```

Sure, `nmod:desc`. These descriptors are mostly for names of persons, which fits.

> Is this a different circumstance? Although I suppose you can't possibly say "Macedonian eastern boder" or "river Nestus" without "the", so these don't count as titles, right?
> 
> ```
> The Macedonian eastern border with Thrace was now secured at the river Nestus (Mesta).
> ```

Right, that's `amod`.

**Comment by AngledLuffa** [comment]
Alright, did the second half in the same PR - would you take a look?

**Pull request merged**
