### PR TITLE
Add Polarity=Neg features to a bunch of no... or un... words in PUD

### PR DESCRIPTION
**Pull request by AngledLuffa**
Change based on similar changes discussed elsewhere in the English UD ecosystem, such as https://github.com/UniversalDependencies/UD_English-EWT/issues/526

### CODE REVIEW

**Comment by AngledLuffa** [comment]
@nschneid @amir-zeldes I take it, based on the discussion in https://github.com/UniversalDependencies/UD_English-EWT/issues/526 that words such as `unprecedented`, `unbelievable`, etc are no longer `Polarity=Neg`?  I tend to agree with @amir-zeldes 's comment that the feature isn't very useful at that point, but I can implement it here if that's the case

**Comment by nschneid** [comment]
Correct, but @amir-zeldes implemented `Negated=Yes` in MISC to cover more cases

**Comment by AngledLuffa** [comment]
I'm a little unmotivated to get such a change right when the models we build won't ever try to predict it.

I guess it's a bit of a rehash of a conversation that already happened, but why not make some sort of morphological feature indicating that kind of negation?

**Comment by nschneid** [comment]
The Core Group concluded that the universal feature should be restricted to the most grammatical negation constructions, as opposed to lexical morphemes containing negative meaning (even if they are semiproductive affixes). IOW *un-* and *in-* and *de-* and *anti-* and so forth can help derive negative words, but they are not the core grammatical system of negation in English, which is pretty much limited to *not* and *no* (+ a few pro-forms).

**Comment by AngledLuffa** [comment]
What was the reasoning, though?

**Comment by nschneid** [comment]
Hard to draw a line if you want to include all words with negative meanings. What about *lack*, *hardly*, *absence*, *disable*, etc.? The feeling was that the FEATS column is mainly for inflectional morphology and function words.

**Comment by AngledLuffa** [comment]
@nschneid updated the PR to only affect `not`.  There were no `no` or `yes` words with INTJ

**Pull request merged**
