### PR TITLE
When treating Spanish as PROPN (for the language), use compound

### PR DESCRIPTION
**Pull request by AngledLuffa**
When treating Spanish as PROPN (for the language), use compound

@nschneid

### CODE REVIEW

**Review by nschneid — APPROVED** [review]

**Comment by dan-zeman** [comment]
Why should Spanish be `PROPN` and not `ADJ`?

**Comment by nschneid** [comment]
Discussed at UniversalDependencies/UD_English-EWT#525. I'm not actually sure about this particular case—could see an argument for either ADJ or PROPN.

**Comment by dan-zeman** [comment]
Hmm, in _Spanish term_ the word _Spanish_ pertains to the language (rather than directly to the country) but it is not the name of the language, it is just an adjective.

I bet that historically _Spanish_ is primarily an adjective, and it was used, among other things, in the expression _Spanish language_ (= the language of Spain), but then the head noun _language_ was more and more often dropped, so now one could say that _Spanish_ alone works as the name of the language (`PROPN`). But if I see the full expression _Spanish language_, I still see an adjective modifying a noun; not a compound!

Admittedly, not every language name works this way. Especially languages that have not been known to Europeans for centuries will have names that are not adjectives in English (or if they are, they may have been derived in the opposite direction).

> Discussed at [UniversalDependencies/UD_English-EWT#525](https://github.com/UniversalDependencies/UD_English-EWT/issues/525).

BTW it is unfortunate that such decisions are found only in the issue tracker, and not even in the docs issue tracker but in a treebank-specific one. Ideally we should document it on the [English PROPN page](https://universaldependencies.org/en/pos/PROPN.html) (which is now outdated, labeled as pertaining to UD v1, and making inappropriate references to a non-UD tagset; same for [ADJ](https://universaldependencies.org/en/pos/ADJ.html)).

**Comment by nschneid** [comment]
Yes, language names in English often have adjective-like endings and overlap with terms used to describe other aspects of the culture.

The de facto details on English parts of speech are found in the Penn Treebank tag guidelines. Those guidelines actually have an explicit policy for language names. We have been moving toward fleshing out the English-specific UPOS guidelines pages (especially where they interface with FEATS), and have done so for ADV, AUX, DET, and PRON—more contributions welcome!

**Pull request merged**
